CREATE DATABASE SQLPROJECT ;
USE SQLPROJECT ;
CREATE TABLE PASSANGERS 
(
P_NAME VARCHAR(20),
P_MO BIGINT PRIMARY KEY,
ARRIVING_LOC VARCHAR(30),
ARRIVING_TIME TIME,
DEPARTURE_LOC VARCHAR(30),
DEPARTURE_TIME TIME,
PAYMENT ENUM('CASH','ONLINE')
);

SELECT * FROM PASSANGERS;

SELECT COUNT(P_NAME) FROM PASSANGERS;

CREATE TABLE OLA
(
SR INT ,
D_NAME VARCHAR(20),
ARRIVING_LOC VARCHAR(30),
ARRIVING_TIME TIME,
OLA_CABID INT PRIMARY KEY ,
OLA_NUMBERPLATE INT ,
COST INT ,
PAYMENT_RACE ENUM('CASH','ONLINE'),
STATUS VARCHAR(30),
P_MO BIGINT,
FOREIGN KEY (P_MO) REFERENCES PASSANGERS (P_MO)
);

INSERT INTO OLA VALUES(1,"SURESH", 7845612347, "HIMATNAGR","12:00:00",111,4455,120,"ONLINE","BOOKED")
SELECT * FROM OLA;
